#!/bin/bash

source do_create.sh

# help message
function print_help() {
program=`echo $0 | awk -F '/' '{print $NF}'`
echo "help:"
echo -e "\t$program (vim)"
}

if (($# < 1)); then
print_help
fi

if [ "$1" == "vim" ]; then
do_vim
fi


