#!/bin/bash

# init program, function:
# backup

dir_home=$HOME
dir_src=`pwd`
dir_backup=$dir_src/.backup

rc_vim=.vimrc

function backupcfg() {
file=`echo $1 | awk -F '/' '{print $NF}'`
echo "backup file: $file ..."
if [ ! -d $dir_backup ]; then
    mkdir $dir_backup
fi
cp $1 $dir_backup/$file"_"`date +%Y%m%d%H%M%S`
}

function check_file() {
if [ -f $1 ]; then
    echo "file $1, exist! backup it"
    backupcfg $1
    rm -rf $1
fi
}

# deal src_file dest_file
function deal() {
check_file $2
ln -s $1 $2
}

echo "link vim rc .. "
deal $dir_src/$rc_vim $dir_home/$rc_vim
echo "finish !"


