#!/bin/bash

alias sudo='sudo env PATH=$PATH'
alias ls='ls --color=auto'
alias ll='ls -lh'
alias lll='ls -alh'
alias grep='grep --exclude=tags --color=auto'
# global adb
alias gadb='/usr/bin/adb'

# REPO
# some repo cannot import REPO_URL, so we transfer it by argument
# eg:
#	repo [option-list] --repo-url=${REPO_URL}
#############################################################################
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'
#alias repo='repo --repo-url=${REPO_URL}'

TOOLS_PATH=$HOME/tools
LINUXCFG_PATH=$HOME/linuxcfg
LINUXCFG_TOOLS_PATH=$LINUXCFG_PATH/home/tools
LXCFG_PATH_TOOLS=${LINUXCFG_PATH}/home/tools

# auto completion
. $HOME/linuxcfg/git-completion.bash

# EDIT THE PATH VARIBLE
#######################

# esp cross tool

ESP_CROSS_TOOL=${LINUXCFG_TOOLS_PATH}/esp/xtensa-esp32-elf
if [ -e ${ESP_CROSS_TOOL}/bin ]; then
	export PATH=${ESP_CROSS_TOOL}/bin:${PATH}
fi

#########
## jdk ##
#########
export JAVA_HOME=$LINUXCFG_TOOLS_PATH/jdk/jdk
if [ -n "$JAVA_HOME" ]; then
export CLASSPATH=$JAVA_HOME/lib
export PATH=$JAVA_HOME/bin:$PATH
fi

# arm linux gcc
export PATH=$TOOLS_PATH/arm_tc/bin:$PATH

##
# PATH env: linuxcfg tools bin and sbin
##
export PATH=${LXCFG_PATH_TOOLS}/bin:${LXCFG_PATH_TOOLS}/sbin:$PATH

## PATH env: home tools
export PATH=$TOOLS_PATH:$PATH
## PATH env: ndk-build
NDK_PATH=$LINUXCFG_TOOLS_PATH/ndk/bin
export PATH=$NDK_PATH:$PATH

. $LINUXCFG_PATH/fcs/user.bashfc

# cd real directory
function cdre() {
cd `pwd -P`
}

# cd .. until find .repo
# if not found .repo, stay current
function croot() {
cur_path=`pwd`
while [ ! -d .repo ]; do
	now_path=`pwd`
	if [ "$now_path" = "/" ]; then
		echo "not found .repo"
		cd $cur_path
		return
	fi
	cd ..
done
}

