if exists("b:vimrc_defined")
	finish
endif
let b:vimrc_defined = 1

if exists("b:vimrc_defined_old")
else
	source ~/linuxcfg/home/user.vimrc
endif

" vim setting of template {{{
augroup vim_setting_template
	autocmd!
	autocmd BufNewFile *.c 0r ~/linuxcfg/home/dotvim/template/tpl.c
	autocmd BufNewFile *.wiki 0r ~/linuxcfg/home/dotvim/template/tpl.wiki
augroup END
" }}}

" the quick keys to edit and save the vimrc
noremap <leader>ev :sp $MYVIMRC<cr>
noremap <leader>sv :source $MYVIMRC<cr>

