#!/bin/bash

function umount_ecryptfs() {
sudo umount -t ecryptfs $efs_mnt_path
}

function mount_ecryptfs() {
if [ ! -d $efs_data_path ]; then mkdir $efs_data_path; fi
if [ ! -d $efs_mnt_path ]; then mkdir $efs_mnt_path; fi

sudo mount -t ecryptfs $efs_data_path $efs_mnt_path -o ecryptfs_cipher=aes -o ecryptfs_key_bytes=16 -o ecryptfs_passthrough=n -o ecryptfs_enable_filename_crypto=y 

}

function quick_dot() {
if [[ ! -f $1 ]]; then
    echo_err "cannot found: $1"
else
    dot -Tpng $1 -O
    eog $1.png &
fi
}

