#!/bin/bash

os=`uname -o`
dir_bashroot=${HOME}/linuxcfg/home/bash

#echo "hello ${os}, ${dir_root}"

if [ "${os}" = "Cygwin" ]; then
	echo "source Cygwin configure"
	source ${dir_bashroot}/cygwin.bashrc
elif [ "${os}" = "Android" ]; then
	source ${dir_bashroot}/android.bashrc
fi

# auto completion
source ${dir_bashroot}/git-completion.bash

# android gradle plugin version is too old, we delay it out-of-work
export ANDROID_DAILY_OVERRIDE=9c8410644eef0398a2466c6c26b401bf3bfdce34
