"		My Vim Configure
" -----------------------------------------------------------
" Author: chenqiwei
" -----------------------------------------------------------

" textwidth
set textwidth=78
" we draw a vertical line to prompt user the textwidth
set colorcolumn=+2
highlight ColorColumn ctermbg=0

" DynamicConfig {{-{
augroup DynamicConfig
autocmd!

" the quick keys to edit and save the vimrc
noremap <leader>ev :sp $MYVIMRC<cr>
noremap <leader>sv :source $MYVIMRC<cr>

"noremap <leader>ss :silent execute "grep! -R " . shellescape(expand("<cWORD>")) . " ."<cr>:copen<cr>
augroup END
""" end of DynamicConfig }}}

if exists("b:vimrc_defined")
	finish
endif
let b:vimrc_defined = 1

if exists("b:vimrc_defined_old")
else
	source ~/linuxcfg/home/user.vimrc
endif

" vim setting of template {{delete this string to wrap script{
augroup vim_setting_template
	autocmd!
	autocmd BufNewFile *.c		0r ~/linuxcfg/home/dotvim/template/tpl.c
	autocmd BufNewFile *.wiki	0r ~/linuxcfg/home/dotvim/template/tpl.wiki
	autocmd BufNewFile *.txt	0r ~/linuxcfg/home/vim/template/tpl.txt
	autocmd BufNewFile *.h		0r ~/linuxcfg/home/vim/template/tpl.h
augroup END
" }}}

""" we use Vundle to manage the plugins
""" setup the Vundle:
"""	mkdir .vim/bundle
"""	git clone https://github.com/VundleVim/Vundle.vim.git
""" add osc ssh key
""" sync other plugins
"""	:BundleUpdate
""" restart the vim
"""
set nocompatible
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'file:///home/e/ct/vim/plugins'
Plugin 'git@git.oschina.net:chss/cundle.git', {'rtp': 'vim/plugins/potion/'}
Plugin 'git@git.oschina.net:chss/vundle-set.git', {'rtp': 'misc/', 'name': 'misc'}
call vundle#end()
filetype plugin indent on

""" vim special hotkey {{{
nnoremap <leader>p :%!kp<cr>
nnoremap <leader>a :%!mvl<cr>
nnoremap <leader>d :%!mvr<cr>
" split qc DDRCS log by symbol z]
nnoremap <leader>fz	:s/z]/z]\r/g<cr>
""" }}}

